### ISSUE TITLE
can we exclude resources?

### ISSUE THREAD

**Issue by marafa-sugarcrm** [aws-samples/aws2tf#26]
can we exclude resources?
eg. i am running aws2tf against an account that belongs to an organisation and i do not have permissions so everytime i run the script it gives me an error on that section

excluding organizations would remove this error

**Comment by awsandy** [comment]
Can you give me an example of what you'd like ?

**Comment by marafa-sugarcrm** [comment]
currently just the organisation to avoid seeing the errors

**Comment by awsandy** [comment]
The start point for aws2tf , is to use and aws cli command to get either a single unique identifier or a list of them to form the basis of a terraform import command.

Unfortunately the aws cli doesn't have a filter by ou option. The "filter" essentially happens when IAM denies access.

The best I could do here is to silently fail those resources.

But that will leave the issue of resources you can access referencing the stuff you were unable to import.

Hence the minimum requirement for aws2tf that you have a minimum of "ReadOnly" access for the resources you are trying to import.

In your case what are the resource types that are in another ou ?

**Comment by marafa-sugarcrm** [comment]
i see .. well we have only one ou
anyways .. it was just a question

thank you
